name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 22
        cache: 'maven'
        cache-dependency-path: './project/pom.xml'
    - name: Build with Maven
      run: mvn -B package --file ./project/pom.xml
